language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - FLAGS=

matrix:
    include:
        - php: 7.0
          env: FLAGS="--exclude-group dwoo"
    allow_failures:
        - php: 7.0
        - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - phpunit --coverage-text $FLAGS